PeerOrgs:
  - Name: Auditor
    Domain: auditor.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
      SANS:
        - localhost
        - 127.0.0.1
        - ::1
    Users:
      Count: 1