OrdererOrgs:
  - Name: Orderer
    Domain: example.com
    EnableNodeOUs: true
    Specs:
      - Hostname: orderer

PeerOrgs:
  - Name: ElectionCommission
    Domain: electioncommission.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1

  - Name: Auditor
    Domain: auditor.example.com
    EnableNodeOUs: true
    Template:
      Count: 1
    Users:
      Count: 1